package com.pat.DAO;

import java.sql.SQLException;
import java.util.List;

import com.pat.modren.event;

public interface eventDAO {
	void save(event event);
    int getEventById(String eventname);
    List<event> getAllEvents();
    void update(event event) throws SQLException;
    void delete(int eventid);
    int retrieveAutoGeneratedOrderId();
	event getEventById(int eventId) throws SQLException;
}
